# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 03:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=120)),
                ('kind', models.CharField(blank=True, max_length=75)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_bid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('minimum_increment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('description', models.TextField()),
                ('situation', models.CharField(max_length=120)),
                ('insurance', models.BooleanField(default=False)),
                ('auction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scrap.Auction')),
            ],
        ),
        migrations.AddField(
            model_name='images',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scrap.Lot'),
        ),
        migrations.AlterUniqueTogether(
            name='auction',
            unique_together=set([('description', 'date')]),
        ),
    ]
