# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 04:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    Company = apps.get_model("scrap", "Company")
    db_alias = schema_editor.connection.alias
    Company.objects.using(db_alias).create(
        name="ML", description="Montenegro Leilões"
    )


def reverse_func(apps, schema_editor):
    Company = apps.get_model("scrap", "Company")
    db_alias = schema_editor.connection.alias
    Company.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0002_lot_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.RunPython(
            forwards_func,
            reverse_func
        ),
        migrations.AlterModelOptions(
            name='auction',
            options={'ordering': ('-date', 'description')},
        ),
        migrations.AlterModelOptions(
            name='lot',
            options={'ordering': ('name', 'description')},
        ),
        migrations.AddField(
            model_name='auction',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scrap.Company'),
            preserve_default=False,
        ),
    ]
